# Uncomment the next line to define a global platform for your project
platform :ios, '12.0'

target 'Mother_Earth' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Mother_Earth
  pod 'RxSwift'
  pod 'RxCocoa'
  pod 'SwiftLint'

end
